server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
mybatis-plus:
  type-aliases-package: cn.bdqn.demo99.entity
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn.bdqn.demo68.mapper: Debug